#!/bin/bash
cd targets/ggml
rm -rf build
mkdir build
cd build
cmake ..  -DCMAKE_C_COMPILER=afl-clang-lto -DCMAKE_CXX_COMPILER=afl-clang-lto++ -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF -DGGML_BUILD_EXAMPLES=OFF -DCMAKE_C_FLAGS="-flto=full" -DCMAKE_LINKER_TYPE=MOLD -DLLAMA_SANITIZE_ADDRESS=ON -DLLAMA_SANITIZE_UNDEFINED=ON -DLLAMA_SANITIZE_THREAD=ON -DLLAMA_BACKEND_DL=OFF -DLLAMA_STATIC=ON -DLLAMA_NATIVE=ON -DLLAMA_LTO=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BACKEND_DL=OFF -DLLAMA_STATIC=ON -DLLAMA_NATIVE=ON -DLLAMA_LTO=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold"
make -j16
