#!/bin/bash
cd targets/ggml
mkdir build
cd build
rm -rf
cmake ..  -DCMAKE_C_COMPILER=afl-clang-lto -DCMAKE_CXX_COMPILER=afl-clang-lto++ -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF -DGGML_BUILD_EXAMPLES=OFF -DCMAKE_C_FLAGS="-flto=full" -DCMAKE_LINKER_TYPE=MOLD #-DGGML_SANITIZE_ADDRESS=ON -DGGML_SANITIZE_UNDEFINED=ON
make -j12