#!/bin/bash
cd targets/llama.cpp
rm -rf build
mkdir build
cd build
AFL_LLVM_LAF_ALL=1 cmake .. -DCMAKE_C_COMPILER=afl-clang-fast -DCMAKE_CXX_COMPILER=afl-clang-fast++ -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF  -DLLAMA_ALL_WARNINGS=OFF -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF -DGGML_BUILD_EXAMPLES=OFF   -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_C_FLAGS="-flto=full -O3" -DCMAKE_CXX_FLAGS="-flto=full -O3"
AFL_LLVM_LAF_ALL=1 make -j12

#-DGGML_SANITIZE_ADDRESS=ON -DGGML_SANITIZE_UNDEFINED=ON -DGGML_SANITIZE_ADDRESS=ON -DGGML_SANITIZE_UNDEFINED=ON -DCMAKE_C_FLAGS="-flto=full" -DGGML_SANITIZE_ADDRESS=ON -DGGML_SANITIZE_UNDEFINED=ON