#!/bin/bash
cd targets/llama.cpp
rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=afl-clang-lto -DCMAKE_CXX_COMPILER=afl-clang-lto++ -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF  -DLLAMA_ALL_WARNINGS=OFF -DBUILD_SHARED_LIBS=OFF -DGGML_BACKEND_DL=OFF -DGGML_STATIC=ON -DGGML_NATIVE=ON -DGGML_LTO=OFF -DGGML_BUILD_EXAMPLES=OFF   -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_C_FLAGS="-flto=full -O3" -DCMAKE_CXX_FLAGS="-flto=full -O3" -DGGML_SANITIZE_ADDRESS=ON -DGGML_SANITIZE_UNDEFINED=ON  -DLLAMA_SANITIZE_ADDRESS=ON -DLLAMA_SANITIZE_UNDEFINED=ON
make -j18
#AFL_LLVM_ALLOWLIST=/home/forrest/fuzzers//llama.cpp.allowlist.txt make -j18
#